database:
  user: weather_station_local
  password: 5NcmIt%Gk6&X6VH8dP
  url: 127.0.0.1
  port: 3306
  db_name: weather_station_v2

resouces:
  path: resources

dataset:
  path: resources/dataset
  download_repositories: resources/download_dataset_map.json
  folder_name_prefix: board_
  board_config_name: board.json
  sensor_name_prefix: s
  checkpoint_path: resources/

model:
  draws_path: model/draws
  checkpoint_path: model/checkpoints
  email_notification: true
  email_receivers:
    - lorenzobergadano@gmail.com
  notifications:
    - END_OF_TRAINING

notification:
  email:
    get_credentials_from_file: true
    username: resources/credentials/email/username.txt
    password: resources/credentials/email/password.txt
    address: smtp.gmail.com
    port: 465
    use_ssl: true